CREATE TABLE libros
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn              VARCHAR(13)                             NOT NULL,
    titulo            VARCHAR(255)                            NOT NULL,
    descripcion       VARCHAR(1000),
    portada_url       VARCHAR(255),
    formato           VARCHAR(255)                            NOT NULL,
    fecha_publicacion date,
    CONSTRAINT pk_libros PRIMARY KEY (id)
);

CREATE TABLE usuario_libros
(
    libro_id   BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT pk_usuario_libros PRIMARY KEY (libro_id, usuario_id)
);

CREATE TABLE usuarios
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre             VARCHAR(50)                             NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    enabled            BOOLEAN                                 NOT NULL,
    fecha_creacion     TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE libros
    ADD CONSTRAINT uc_libros_isbn UNIQUE (isbn);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_email UNIQUE (email);

ALTER TABLE usuario_libros
    ADD CONSTRAINT fk_usulib_on_catalogo_libros FOREIGN KEY (libro_id) REFERENCES libros (id);

ALTER TABLE usuario_libros
    ADD CONSTRAINT fk_usulib_on_gestion_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios (id);